name:                 hft
version:              0.1.0.0
visibility:           public
id:                   hft-0.1.0.0-inplace
key:                  hft-0.1.0.0-inplace
maintainer:           j.willis19@imperial.ac.uk
author:               Imperial College London
synopsis:             Haskell Final Test 22
abi:                  inplace
exposed:              True
exposed-modules:      Examples SC Types
import-dirs:
    "/mnt/c/Users/katie/Computing/computing-notes/Year 1/COMP40009 Computing Practical 1/Haskell/Finals/2022/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hft-0.1.0.0/build"

library-dirs:
    "/mnt/c/Users/katie/Computing/computing-notes/Year 1/COMP40009 Computing Practical 1/Haskell/Finals/2022/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hft-0.1.0.0/build"

library-dirs-static:
    "/mnt/c/Users/katie/Computing/computing-notes/Year 1/COMP40009 Computing Practical 1/Haskell/Finals/2022/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hft-0.1.0.0/build"

dynamic-library-dirs:
    "/mnt/c/Users/katie/Computing/computing-notes/Year 1/COMP40009 Computing Practical 1/Haskell/Finals/2022/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hft-0.1.0.0/build"

data-dir:
    "/mnt/c/Users/katie/Computing/computing-notes/Year 1/COMP40009 Computing Practical 1/Haskell/Finals/2022/."

hs-libraries:         HShft-0.1.0.0-inplace
depends:              base-4.18.3.0 containers-0.6.7
haddock-interfaces:
    "/mnt/c/Users/katie/Computing/computing-notes/Year 1/COMP40009 Computing Practical 1/Haskell/Finals/2022/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hft-0.1.0.0/doc/html/hft/hft.haddock"

haddock-html:
    "/mnt/c/Users/katie/Computing/computing-notes/Year 1/COMP40009 Computing Practical 1/Haskell/Finals/2022/dist-newstyle/build/x86_64-linux/ghc-9.6.7/hft-0.1.0.0/doc/html/hft"
